---
title: "Test2"
output: html_document
date: '2022-08-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(corrplot)
library(ggplot2)
library(tidyverse)  # data manipulation
library(cluster)	# clustering algorithms
library(factoextra) # clustering visualization
library(dendextend) # for comparing two dendrograms
```


```{r}
library(dplyr)
```


```{r}
head(diamonds)
diamondsbackup <- diamonds
```

```{r}
set.seed(2000)
diamonds2  <- sample_n(diamonds,17000)
head(diamonds2)


```

```{r}
cobain <-unclass(diamonds2$cut)
diamonds2$cut <- cobain

diamonds2$color2[diamonds2$color =="J" ] <-1 
diamonds2$color2[diamonds2$color =="I" ] <-2 
diamonds2$color2[diamonds2$color =="H" ] <-3 
diamonds2$color2[diamonds2$color =="G" ] <-4 
diamonds2$color2[diamonds2$color =="F" ] <-5 
diamonds2$color2[diamonds2$color =="E" ] <-6 
diamonds2$color2[diamonds2$color =="D" ] <-7 

diamonds2$clarity2[diamonds2$clarity=="I1"] <-1
diamonds2$clarity2[diamonds2$clarity=="SI2"] <-2
diamonds2$clarity2[diamonds2$clarity=="SI1"] <-3
diamonds2$clarity2[diamonds2$clarity=="VS2"] <-4
diamonds2$clarity2[diamonds2$clarity=="VS1"] <-5
diamonds2$clarity2[diamonds2$clarity=="VVS2"] <-6
diamonds2$clarity2[diamonds2$clarity=="VVS1"] <-7
diamonds2$clarity2[diamonds2$clarity=="IF1"] <-8


head(diamonds2)
```



```{r}
numeric_predictors=c('carat',"price","x","y","z","clarity2")
df <- diamonds2[,numeric_predictors]
df <-  subset(df, x!=0 & y!=0 & z!=0 & carat!=0  & price!=0  & clarity2!=0)
dim(df)
```


```{r}
my_range <- 1:15
for(i in my_range){
quartiles <- quantile(df$carat, probs=c(.25, .75), na.rm = FALSE)
IQR <- IQR(df$carat)
Lower <- quartiles[1] - 1.5*IQR
Upper <- quartiles[2] + 1.5*IQR
df <- subset(df, df$carat > Lower & df$carat < Upper)
print(dim(df))


quartiles3 <- quantile(df$price, probs=c(.25, .75), na.rm = FALSE)
IQR <- IQR(df$price)
Lower <- quartiles3[1] - 1.5*IQR
Upper <- quartiles3[2] + 1.5*IQR
df <- subset(df, df$price > Lower & df$price < Upper)
print(dim(df))



}

df <- subset(df, x!=0 & y!=0 & z!=0)
print(dim(df))

```


```{r}
library(psych)
KMO(r=cor(df))
```

```{r}
df_no_scale <- df
df_no_scale <- na.omit(df_no_scale)
```



```{r}
df <- na.omit(df)
df <- scale(df)
```



#Begin Clustering
```{r}
k2 <- kmeans(df, centers = 2, nstart = 25)
k2
```

```{r}
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)

# plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```
```{r}
set.seed(123)

# function to compute total within-cluster sum of square
wss <- function(k) {
  kmeans(df, k, nstart = 10 )$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)

plot(k.values, wss_values,
   	type="b", pch = 19, frame = FALSE,
   	xlab="Number of clusters K",
   	ylab="Total within-clusters sum of squares")
```
```{r}
fviz_nbclust(df, kmeans, method = "silhouette")
```

```{r}
# Compute k-means clustering with k = 3
set.seed(123)
final <- kmeans(df, 3, nstart = 25)
print(final)
```

## PCA

```{r}
library("devtools")
#install_github("kassambara/factoextra")
```

```{r}
library("factoextra")
```


```{r}
head(df_no_scale)
```

```{r}
res.pca <- princomp(df,cor = TRUE)
```

```{r}
ind <- get_pca_ind(res.pca)
ind
```

```{r}
final_pca <- ind$coord
head(final_pca)
```

```{r}
summary(res.pca, loadings = TRUE)
```

```{r}
pca_selected <- subset(final_pca, select = c(Dim.1, Dim.2) )
pca_selected2 <- pca_selected
```

```{r}
head(pca_selected)
```



```{r}
kpca <- kmeans(pca_selected, centers = 3, nstart = 25)
kpca
```

```{r}
set.seed(123)

# function to compute total within-cluster sum of square 
wss <- function(k) {
  kmeans(pca_selected, k, nstart = 10 )$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)

plot(k.values, wss_values,
       type="b", pch = 19, frame = FALSE, 
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
```

```{r}
k3 <- kmeans(pca_selected, centers = 3, nstart = 25)
k4 <- kmeans(pca_selected, centers = 4, nstart = 25)
k5 <- kmeans(pca_selected, centers = 5, nstart = 25)

# plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = pca_selected) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = pca_selected) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = pca_selected) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = pca_selected) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```

```{r}
df$cluster <-final$cluster
```

```{r}
df_no_scale$cluster <-final$cluster
```

```{r}
df_no_scale
```

```{r}
head(pca_selected2)
pca_selected2 <- data.frame(pca_selected2)
```

```{r}
pca_selected2$cluster <-final$cluster
```

```{r}
pca_selected2
```

